version: 3

silent: true

tasks:
  venv:
    cmds:
      - cmd: |
          python3 -m venv .venv

  install:
    cmds:
      - cmd: brew install libomp openblas
        platforms: [darwin]
      - cmd: |
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -U -r requirements.txt
        platforms: ["linux", "darwin"]
      - cmd: |
          python3 -m venv .venv
          .venv\Scripts\activate
          python -m pip install --upgrade pip
          pip install -U -r requirements.txt
        platforms: ["windows"]

  start:
    cmds:
      - |
        source .venv/bin/activate
        uvicorn app.api.server:app --host 0.0.0.0 --port 3000 --reload

  add-document:
    requires:
      vars:
        - file
    cmds:
      - |
        source .venv/bin/activate
        python client/memsplora_cli.py add-document --mode "advanced" --collection-id iirds "{{.file}}"
  search:
    requires:
      vars:
        - query
    cmds:
      - |
        source .venv/bin/activate
        python client/memsplora_cli.py search --mode "advanced" --collection-id iirds "{{.query}}" --min-score 0.8 --top-k 5
